[build]
  publish = "build
  command = "yarn build"

[context.production.environment]
  REACT_APP_ENV = "production"

[context.branch-deploy.environment]
  REACT_APP_ENV = "development"

[[redirects]]
  from = "/*"
  to = "/"
